-- ============================================================
-- Pi Bazaar — Phase 7: Platform Revenue & Admin Moderation
-- ============================================================
-- SECURITY NOTE: All RLS policies use auth.jwt() ->> 'pi_uid'
-- to read the pi_uid claim from the verified custom JWT signed
-- by our server — consistent with all prior migrations.
-- ============================================================

-- ─── Add role column to users ────────────────────────────────────────────────
-- Restricts values to 'user' (default) or 'admin'. Only the service-role
-- client (supabaseAdmin) can update this column since there is no client
-- UPDATE policy on the users table.
ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'user'
    CHECK (role IN ('user', 'admin'));

-- ─── Add is_suspended flag to users ──────────────────────────────────────────
-- When true, the user's account is suspended by an admin.
ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS is_suspended BOOLEAN NOT NULL DEFAULT false;

-- ─── Extend listings.status to include 'suspended' ──────────────────────────
-- Drop the existing CHECK constraint and recreate it with the new value.
-- The constraint name comes from 01_init_schema.sql (auto-generated by
-- Postgres for inline CHECK on the status column).
ALTER TABLE public.listings
  DROP CONSTRAINT IF EXISTS listings_status_check;

ALTER TABLE public.listings
  ADD CONSTRAINT listings_status_check
    CHECK (status IN ('active', 'sold', 'removed', 'suspended'));

-- ─── platform_revenue ────────────────────────────────────────────────────────
-- Tracks the platform fee collected from each successful escrow release.
CREATE TABLE IF NOT EXISTS public.platform_revenue (
  id           UUID           PRIMARY KEY DEFAULT gen_random_uuid(),
  escrow_id    UUID           NOT NULL REFERENCES public.escrow_transactions(id) ON DELETE RESTRICT,
  amount_pi    NUMERIC(20, 7) NOT NULL CHECK (amount_pi > 0),
  collected_at TIMESTAMPTZ    NOT NULL DEFAULT now()
);

-- Enforce one fee record per escrow transaction while still supporting fast lookups.
CREATE UNIQUE INDEX IF NOT EXISTS platform_revenue_escrow_idx
  ON public.platform_revenue (escrow_id);

-- Index for time-range aggregation queries on the admin dashboard
CREATE INDEX IF NOT EXISTS platform_revenue_collected_at_idx
  ON public.platform_revenue (collected_at);

-- ─── RLS: platform_revenue ───────────────────────────────────────────────────
ALTER TABLE public.platform_revenue ENABLE ROW LEVEL SECURITY;

-- Only admin users may read platform revenue records via the client.
-- In practice, admin routes use supabaseAdmin (service role) which bypasses
-- RLS, but this policy provides defence-in-depth.
CREATE POLICY "platform_revenue_select_admin"
  ON public.platform_revenue FOR SELECT
  USING (
    auth.role() = 'authenticated'
    AND EXISTS (
      SELECT 1 FROM public.users
      WHERE pi_uid = (auth.jwt() ->> 'pi_uid')
        AND role = 'admin'
    )
  );

-- No INSERT / UPDATE / DELETE policies — all mutations go through the
-- service-role client (supabaseAdmin) in server-side API routes.

-- ─── Revenue aggregation function ────────────────────────────────────────────
-- Called from the admin analytics API via supabaseAdmin.rpc().
-- SECURITY DEFINER so it bypasses RLS when executed by the service role.
CREATE OR REPLACE FUNCTION public.get_total_platform_revenue()
RETURNS NUMERIC LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  RETURN COALESCE(
    (SELECT SUM(amount_pi) FROM public.platform_revenue),
    0
  );
END;
$$;
