// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pibazaar-redesign/BoldCommerce.tsx": () => import("../components/mockups/pibazaar-redesign/BoldCommerce.tsx"),
  "./components/mockups/pibazaar-redesign/MarketplaceModern.tsx": () => import("../components/mockups/pibazaar-redesign/MarketplaceModern.tsx"),
  "./components/mockups/pibazaar-redesign/PiPremium.tsx": () => import("../components/mockups/pibazaar-redesign/PiPremium.tsx")
};
